INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 1, 'Atendimento horrível.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 1, 'Muito tempo de espera e atendimento ruim.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 1, 'Não fui bem atendido.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 1, 2, 1, 'Não recomendo, péssima experiência.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 2, 2, 1, 'Desorganização total.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 3, 2, 1, 'Fui ignorado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 1, 3, 1, 'O atendimento foi muito ruim.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 2, 3, 1, 'Não gostei, total falta de profissionalismo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 3, 3, 1, 'Não resolveram o meu problema.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 1, 1, 1, 'Atendimento péssimo, demorado e sem qualidade.');

INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 1, 1, 'A clínica estava suja.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 3, 1, 1, 'Não voltaria nunca.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 1, 2, 1, 'Completamente insatisfeito com o serviço.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 2, 2, 1, 'Não consegui resolver meu problema com eles.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 3, 2, 1, 'Muito insatisfeito com o atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 1, 3, 1, 'Falta de respeito com o cliente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 2, 3, 1, 'Pior consulta que já tive.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 3, 3, 1, 'Profissional despreparado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 1, 1, 1, 'Atendimento muito aquém do esperado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 2, 1, 1, 'Atendimento razoável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (1, 2, 1, 1, 'Uma experiência desastrosa.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (2, 1, 1, 2, 'Esperava mais do atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (3, 2, 1, 2, 'Fui atendido, mas com muitos problemas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (4, 3, 1, 2, 'Não foi um bom atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (5, 1, 2, 2, 'Serviço abaixo do esperado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (6, 2, 2, 2, 'Atendimento razoável, mas com falhas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (7, 3, 2, 2, 'Pouca atenção aos detalhes.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (8, 1, 3, 2, 'Atendimento muito corrido e sem cuidado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (9, 2, 3, 2, 'Demorou muito para ser atendido.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, avaliacao, comentario) VALUES (10, 3, 3, 2, 'O atendimento não foi satisfatório.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 2, 'Faltou organização e eficiência.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 2, 'Experiência decepcionante.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 2, 'Muitos atrasos e pouca atenção.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 1, 2, 2, 'Achei que poderiam ser mais atenciosos.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 2, 2, 2, 'Serviço ok, mas com margem para melhora.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 3, 2, 2, 'Faltou profissionalismo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 1, 3, 2, 'Serviço lento e desorganizado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 2, 3, 2, 'Demoraram muito para me atender.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 3, 3, 2, 'Pouco cuidado e atenção durante a consulta.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 1, 1, 2, 'Faltou atenção ao cliente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 2, 'Deixou a desejar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 1, 1, 2, 'Não fiquei satisfeito com o serviço.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 1, 1, 3, 'Atendimento razoável, mas pode melhorar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 1, 1, 3, 'Não foi ruim, mas esperava mais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 1, 1, 3, 'O serviço foi mediano.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 1, 2, 3, 'Tudo ocorreu de forma aceitável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 2, 2, 3, 'Nada de especial, atendimento ok.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 3, 2, 3, 'Foi uma experiência regular.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 1, 3, 3, 'Atendimento dentro do esperado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 3, 3, 'Consulta mediana, sem grandes problemas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 3, 3, 3, 'O serviço foi ok, sem nada demais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 1, 1, 3, 'Atendimento regular, nada de mais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 2, 1, 3, 'Foi tudo bem, mas podia ser melhor.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 3, 1, 3, 'Consulta normal, nada excepcional.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 1, 2, 3, 'Atendimento regular, sem grandes problemas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 2, 2, 3, 'Foi uma consulta ok, mas poderia melhorar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 3, 2, 3, 'Tudo dentro do esperado, mas nada de especial.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 1, 3, 3, 'Esperava um pouco mais, mas foi razoável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 2, 3, 3, 'Consulta normal, sem problemas graves.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 1, 4, 'Bom atendimento e profissionalismo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 3, 1, 4, 'Gostei bastante do atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 1, 2, 4, 'Fui bem atendido e fiquei satisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 2, 2, 4, 'Ambiente agradável e atendimento de qualidade.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 3, 2, 4, 'Muito bom, com certeza voltarei.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 1, 3, 4, 'Experiência bem positiva.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 2, 3, 4, 'Fui bem atendido, consulta eficiente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 3, 1, 4, 'Profissional atencioso, tudo foi ótimo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 1, 1, 4, 'Gostei muito da atenção que recebi.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 2, 1, 4, 'Consulta boa e sem problemas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 2, 4, 'Atendimento muito satisfatório.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 3, 2, 4, 'Bom atendimento e ambiente limpo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 1, 3, 4, 'Muito bom, recomendo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 2, 3, 4, 'Consulta boa e sem complicações.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 3, 3, 4, 'Atendimento bom e rápido.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 1, 1, 4, 'Muito satisfeito com o atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 2, 1, 4, 'Profissional bem preparado, foi tudo ótimo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 1, 1, 5, 'Atendimento excelente, recomendo!');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 2, 1, 5, 'Ótima experiência, fui muito bem atendido.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 3, 1, 5, 'Profissionais muito atenciosos e capacitados.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 2, 5, 'Muito satisfeito com a qualidade do serviço.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 3, 2, 5, 'Atendimento excepcional, vou voltar com certeza.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 1, 3, 5, 'Excelente atendimento, equipe muito qualificada.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 2, 3, 5, 'O serviço foi perfeito, melhor clínica que já fui.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 3, 3, 5, 'Muito satisfeito, atendimento de primeira.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 1, 1, 5, 'Equipe muito atenciosa e tratamento de alta qualidade.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 2, 1, 5, 'Tudo impecável, recomendo fortemente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 3, 1, 5, 'Atendimento excelente, fui muito bem recebido.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 1, 2, 5, 'Muito satisfeito, atendimento exemplar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 2, 2, 5, 'Ótimo atendimento, nota 10.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 3, 2, 5, 'Serviço de excelência, sem defeitos.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 1, 3, 5, 'Excelente atendimento, com certeza recomendo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 2, 3, 5, 'Consulta perfeita, tudo correu muito bem.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 3, 3, 5, 'Ótimo atendimento, muito satisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 1, 1, 5, 'Atendimento nota 10, recomendo para todos.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 2, 1, 5, 'Atendimento excelente, superou minhas expectativas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 1, 1, 3, 'O atendimento foi suficiente, mas sem grandes surpresas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 2, 1, 3, 'Foi razoável, mas poderia ter sido mais atencioso.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 3, 1, 3, 'A consulta foi aceitável, porém com melhorias a fazer.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 1, 2, 3, 'O serviço foi regular, sem muito destaque.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (11, 2, 2, 3, 'Atendimento foi mediano, podia ter mais atenção.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 3, 2, 3, 'Consulta razoável, mas poderia melhorar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 1, 3, 3, 'O atendimento foi ok, mas nada de especial.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 2, 3, 3, 'Consulta normal, atendimento básico.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 3, 3, 3, 'Foi dentro do esperado, sem grandes problemas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 1, 1, 3, 'A consulta foi ok, mas não houve nada de diferente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 2, 1, 3, 'Fui atendido, mas o serviço foi apenas razoável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 3, 1, 3, 'Atendimento dentro do padrão, mas sem grandes qualidades.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 1, 2, 3, 'O serviço foi ok, mas não me surpreendeu.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 2, 2, 3, 'Foi um atendimento simples, sem grandes diferenciais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 3, 2, 3, 'Consulta foi regular, mas nada impressionante.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 3, 3, 'Atendimento padrão, nada de novo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 3, 3, 3, 'Fui atendido de maneira adequada, mas sem destaques.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 3, 'Atendimento simples, razoável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 1, 3, 'Consulta foi ok, mas com alguns pontos a melhorar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 4, 'Consulta agradável e bom atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 1, 4, 'Foi um bom serviço, estou satisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 3, 1, 4, 'Fiquei satisfeito com o atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 2, 4, 'O atendimento foi bom, tudo correu bem.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 2, 2, 4, 'Ambiente agradável e ótimo serviço.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 3, 2, 4, 'Muito satisfeito com o resultado da consulta.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 3, 4, 'Ótima consulta, serviço de qualidade.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 4, 'Atendimento foi muito bom, gostei.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 5, 'Consulta realizada com sucesso, muito bom.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 4, 'Atendimento foi muito positivo, recomendo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 1, 2, 3, 'Tudo ocorreu conforme o esperado, ótimo serviço.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (5, 2, 2, 5, 'Profissionais atenciosos, gostei muito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (6, 3, 2, 4, 'Bom atendimento, recomendo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (7, 1, 3, 4, 'Consulta agradável, serviço bom.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (8, 2, 3, 5, 'Gostei bastante do atendimento, foi muito bom.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (9, 3, 3, 4, 'Fui bem atendido e me senti confortável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (10, 1, 1, 3, 'Atendimento foi bom, tudo tranquilo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 4, 'Muito bom, serviço de qualidade.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 4, 'Profissionais bem preparados, ótimo atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 5, 'Atendimento perfeito, nada a reclamar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 5, 'Fui muito bem atendido, excelente equipe.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 5, 'Ótima consulta, profissionais capacitados.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 2, 5, 'Equipe maravilhosa, fui muito bem recebido.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 2, 5, 'Atendimento excepcional, superou expectativas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 2, 5, 'Clínica de excelência, adorei o atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 3, 5, 'Muito bom, atendimento impecável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 3, 5, 'Serviço incrível, tudo perfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 3, 5, 'Consulta excelente, recomendaria a todos.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 5, 'Fiquei muito satisfeito, foi perfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 5, 'Profissionais de alto nível, atendimento impecável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 5, 'Fui extremamente bem tratado, perfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 2, 5, 'Atendimento maravilhoso, melhor impossível.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 2, 5, 'Clínica excelente, tudo impecável.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 2, 5, 'Fui tratado com muito cuidado, excelente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 3, 5, 'Serviço excepcional, nota máxima.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 3, 5, 'Consulta excelente, recomendo a todos.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 3, 5, 'Profissionais altamente qualificados.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 5, 'Experiência incrível, sem falhas.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 5, 'Atendimento perfeito, super recomendo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 1, 'Atendimento péssimo, não recomendo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 1, 'Consulta horrível, muito insatisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 1, 'Não gostei, atendimento terrível.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 2, 1, 'Muito ruim, falta de profissionalismo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 2, 1, 'Total falta de atenção, não volto mais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 2, 1, 'Fui muito mal atendido, péssimo serviço.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 3, 1, 'Atendimento desastroso, não recomendo a ninguém.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 3, 1, 'Consulta completamente insatisfatória.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 3, 1, 'Horrível, a pior consulta que já fiz.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 1, 'Foi péssimo, não volto mais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 1, 'Experiência horrível, fiquei muito insatisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 1, 'Atendimento abaixo de qualquer expectativa, péssimo.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 2, 1, 'Serviço terrível, total falta de atenção.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 2, 1, 'Péssimo atendimento, saí muito insatisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 2, 1, 'Não fui bem tratado, atendimento horrível.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 3, 1, 'Consulta ruim, péssimo ambiente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 3, 1, 'Horrível, não recomendo para ninguém.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 3, 1, 'Experiência péssima, fiquei muito decepcionado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 1, 'Total falta de respeito com o paciente.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 1, 'Atendimento horrível, jamais voltarei.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 2, 'Atendimento fraco, faltou cuidado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 2, 'Consulta deixou muito a desejar.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 2, 'Não foi uma boa experiência, bastante ruim.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 2, 2, 'Atendimento fraco, esperava mais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 2, 2, 'O serviço foi ruim, faltou atenção.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 2, 2, 'Consulta abaixo do esperado, atendimento ruim.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 3, 2, 'Serviço ruim, não fiquei satisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 3, 2, 'Foi um atendimento ruim, não volto mais.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 3, 2, 'Faltou atenção e cuidado, atendimento ruim.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 1, 2, 'Consulta ruim, esperava mais cuidado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 1, 2, 'Atendimento muito fraco, fiquei decepcionado.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 3, 1, 2, 'Serviço ruim, não volto mais a essa clínica.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (1, 1, 2, 2, 'Consulta fraca, faltou atenção do dentista.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 2, 2, 2, 'Experiência ruim, muito insatisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (2, 3, 2, 2, 'Não foi bom, faltou mais cuidado no atendimento.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 1, 3, 2, 'Consulta decepcionante, serviço ruim.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (3, 2, 3, 2, 'O atendimento foi fraco, fiquei insatisfeito.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 3, 3, 2, 'Não gostei da consulta, serviço ruim.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 1, 1, 2, 'Foi um atendimento ruim, faltou atenção.');
INSERT INTO Feedback (fk_id_cliente, fk_id_especialista, fk_id_clinica, nota, comentario) VALUES (4, 2, 1, 2, 'Consulta ruim, esperava mais cuidado.');



